from types import SimpleNamespace

import pytest
from fastapi import HTTPException

from routers import identity as identity_router
from routers.identity import LocationUpdateRequest, update_profile_location

real_verify_signature = identity_router.verify_signature


class ScalarResult:
    def __init__(self, value):
        self.value = value

    def scalar_one_or_none(self):
        return self.value


class FakeDb:
    def __init__(self, values):
        self.values = list(values)
        self.commits = 0
        self.statements = []

    async def execute(self, statement):
        self.statements.append(statement)
        return ScalarResult(self.values.pop(0))

    async def commit(self):
        self.commits += 1


def active_identity():
    return SimpleNamespace(
        region_locked=False,
        periferia_id=None,
        dimos_id=None,
        public_key_hex="c" * 64,
    )


@pytest.fixture(autouse=True)
def valid_signature(monkeypatch):
    monkeypatch.setattr(identity_router, "verify_signature", lambda *_args: True)


def request(**kwargs):
    return LocationUpdateRequest(
        nullifier_hash="a" * 64,
        signature_hex="b" * 128,
        **kwargs,
    )


@pytest.mark.asyncio
async def test_dimos_derives_authoritative_periferia_and_locks():
    record = active_identity()
    db = FakeDb([record, SimpleNamespace(id=22, periferia_id=6)])
    result = await update_profile_location(
        request(dimos_id=22),
        db,
    )
    assert result == {
        "success": True,
        "periferia_id": 6,
        "dimos_id": 22,
        "region_locked": True,
    }
    assert db.commits == 1
    assert "FOR UPDATE" in str(db.statements[0])


@pytest.mark.asyncio
async def test_mismatched_dimos_and_periferia_is_rejected_without_commit():
    db = FakeDb([active_identity(), SimpleNamespace(id=22, periferia_id=6)])
    with pytest.raises(HTTPException) as exc:
        await update_profile_location(
            request(periferia_id=7, dimos_id=22),
            db,
        )
    assert exc.value.status_code == 400
    assert db.commits == 0


@pytest.mark.asyncio
async def test_unknown_dimos_is_rejected_without_commit():
    db = FakeDb([active_identity(), None])
    with pytest.raises(HTTPException) as exc:
        await update_profile_location(
            request(dimos_id=99999),
            db,
        )
    assert exc.value.status_code == 400
    assert db.commits == 0


@pytest.mark.asyncio
async def test_valid_periferia_without_dimos_is_supported():
    record = active_identity()
    db = FakeDb([record, SimpleNamespace(id=6)])
    result = await update_profile_location(
        request(periferia_id=6),
        db,
    )
    assert result["periferia_id"] == 6
    assert result["dimos_id"] is None
    assert result["region_locked"] is True


@pytest.mark.asyncio
async def test_invalid_location_signature_is_rejected_before_geography_lookup(monkeypatch):
    monkeypatch.setattr(identity_router, "verify_signature", lambda *_args: False)
    db = FakeDb([active_identity()])
    with pytest.raises(HTTPException) as exc:
        await update_profile_location(request(periferia_id=6), db)
    assert exc.value.status_code == 401
    assert db.commits == 0


@pytest.mark.asyncio
async def test_mobile_ed25519_location_vector_verifies_on_backend(monkeypatch):
    """Cross-language vector generated by the mobile Noble Ed25519 implementation."""
    monkeypatch.setattr(identity_router, "verify_signature", real_verify_signature)
    record = active_identity()
    record.public_key_hex = "8139770ea87d175f56a35466c34c7ecccb8d8a91b4ee37a25df60f5b8fc9b394"
    db = FakeDb([record, SimpleNamespace(id=22, periferia_id=6)])
    result = await update_profile_location(
        LocationUpdateRequest(
            nullifier_hash="n" * 64,
            periferia_id=6,
            dimos_id=22,
            signature_hex=(
                "3ee9e65a2e1c3bd1b084036129598080e2095001adb4ebabbdb4d5299efffbb9f"
                "24e1af3f214bc3c4065e6a47549843dcad5a757bd059af6a022dd158715400d"
            ),
        ),
        db,
    )
    assert result["region_locked"] is True
    assert result["periferia_id"] == 6
    assert result["dimos_id"] == 22
