import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  // ── ECONOMIC (E1-E24) ──────────────────────────────────────
  { id: "E1", text: "Ο κράτος πρέπει να αυξήσει τη φορολογία για να μειώσει τις κοινωνικές ανισότητες.", axis: "economic", reverse: false, weight: 1.0 },
  { id: "E2", text: "Η ελεύθερη αγορά είναι πιο αποτελεσματική από το κράτος στην κατανομή πόρων.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E3", text: "Οι ιδιωτικοποιήσεις δημόσιων υπηρεσιών ωφελούν την οικονομία.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E4", text: "Το κράτος πρέπει να προστατεύει τους εργαζόμενους ακόμη και αν περιορίζει τις επιχειρήσεις.", axis: "economic", reverse: false, weight: 1.0 },
  { id: "E5", text: "Η φοροδιαφυγή είναι κατανοητή σε περιόδους οικονομικής κρίσης.", axis: "economic", reverse: true, weight: 0.8 },
  { id: "E6", text: "Η Ελλάδα πρέπει να διατηρήσει ισχυρό δημόσιο τομέα.", axis: "economic", reverse: false, weight: 1.0 },
  { id: "E7", text: "Οι κοινωνικές παροχές μειώνουν το κίνητρο για εργασία.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E8", text: "Το κράτος πρέπει να εγγυάται βασικό εισόδημα για όλους.", axis: "economic", reverse: false, weight: 1.2 },
  { id: "E9", text: "Η Ευρωπαϊκή Ένωση περιορίζει υπερβολικά την οικονομική ανεξαρτησία της Ελλάδας.", axis: "economic", reverse: false, weight: 0.9 },
  { id: "E10", text: "Οι μεγάλες επιχειρήσεις πρέπει να έχουν λιγότερους κανονισμούς.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E11", text: "Η αναδιανομή πλούτου είναι απαραίτητη για μια δίκαιη κοινωνία.", axis: "economic", reverse: false, weight: 1.1 },
  { id: "E12", text: "Η οικονομική ανάπτυξη είναι πιο σημαντική από την κοινωνική ισότητα.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E13", text: "Οι μισθοί πρέπει να καθορίζονται κυρίως από την αγορά.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E14", text: "Το κράτος πρέπει να παρεμβαίνει για να αποτρέπει μεγάλες ανισότητες εισοδήματος.", axis: "economic", reverse: false, weight: 1.1 },
  { id: "E15", text: "Οι δημόσιες υπηρεσίες λειτουργούν πιο αποτελεσματικά όταν είναι ιδιωτικές.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E16", text: "Το κράτος πρέπει να υποστηρίζει ενεργά μικρές επιχειρήσεις.", axis: "economic", reverse: false, weight: 1.0 },
  { id: "E17", text: "Η φορολογία στις επιχειρήσεις πρέπει να μειωθεί για να ενισχυθεί η ανάπτυξη.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E18", text: "Η κοινωνική πρόνοια είναι βασική ευθύνη του κράτους.", axis: "economic", reverse: false, weight: 1.1 },
  { id: "E19", text: "Οι αγορές πρέπει να λειτουργούν χωρίς κρατική παρέμβαση.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E20", text: "Η ανισότητα είναι αποδεκτή αν οδηγεί σε ανάπτυξη.", axis: "economic", reverse: true, weight: 0.9 },
  { id: "E21", text: "Το κράτος πρέπει να εγγυάται εργασία για όλους.", axis: "economic", reverse: false, weight: 1.2 },
  { id: "E22", text: "Οι δημόσιες δαπάνες πρέπει να περιοριστούν σημαντικά.", axis: "economic", reverse: true, weight: 1.0 },
  { id: "E23", text: "Η οικονομική πολιτική πρέπει να καθορίζεται κυρίως από εθνικούς θεσμούς και όχι από την ΕΕ.", axis: "economic", reverse: false, weight: 0.9 },
  { id: "E24", text: "Οι κοινωνικές παροχές πρέπει να μειωθούν για να μειωθεί το δημόσιο χρέος.", axis: "economic", reverse: true, weight: 1.0 },
  // ── SOCIAL (S1-S24) ────────────────────────────────────────
  { id: "S1", text: "Η ασφάλεια είναι πιο σημαντική από την ατομική ελευθερία.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S2", text: "Το κράτος δεν πρέπει να παρακολουθεί τους πολίτες χωρίς σοβαρό λόγο.", axis: "social", reverse: true, weight: 1.0 },
  { id: "S3", text: "Η μετανάστευση πρέπει να ελέγχεται αυστηρά.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S4", text: "Οι άνθρωποι πρέπει να έχουν πλήρη ελευθερία στις προσωπικές επιλογές τους.", axis: "social", reverse: true, weight: 1.0 },
  { id: "S5", text: "Η εκκλησία πρέπει να έχει σημαντικό ρόλο στην κοινωνία.", axis: "social", reverse: false, weight: 0.9 },
  { id: "S6", text: "Το κράτος πρέπει να είναι πλήρως διαχωρισμένο από την εκκλησία.", axis: "social", reverse: true, weight: 1.0 },
  { id: "S7", text: "Οι παραδοσιακές αξίες πρέπει να διατηρηθούν ακόμη και αν περιορίζουν την ελευθερία.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S8", text: "Η ελευθερία έκφρασης πρέπει να προστατεύεται ακόμη και για ακραίες απόψεις.", axis: "social", reverse: true, weight: 1.1 },
  { id: "S9", text: "Η αστυνομία πρέπει να έχει περισσότερες εξουσίες για να διατηρεί την τάξη.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S10", text: "Οι πολίτες πρέπει να έχουν δικαίωμα να αμφισβητούν την εξουσία χωρίς φόβο.", axis: "social", reverse: true, weight: 1.0 },
  { id: "S11", text: "Η λογοκρισία μπορεί να είναι απαραίτητη για την κοινωνική σταθερότητα.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S12", text: "Η ιδιωτικότητα είναι θεμελιώδες δικαίωμα που δεν πρέπει να παραβιάζεται.", axis: "social", reverse: true, weight: 1.2 },
  { id: "S13", text: "Η δημόσια τάξη πρέπει να διατηρείται ακόμη και με περιορισμό δικαιωμάτων.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S14", text: "Οι πολίτες πρέπει να έχουν πλήρη ελευθερία στην έκφραση πολιτικών απόψεων.", axis: "social", reverse: true, weight: 1.0 },
  { id: "S15", text: "Η μετανάστευση εμπλουτίζει την κοινωνία.", axis: "social", reverse: true, weight: 1.0 },
  { id: "S16", text: "Οι αυστηροί νόμοι είναι απαραίτητοι για μια σταθερή κοινωνία.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S17", text: "Η κυβέρνηση δεν πρέπει να επεμβαίνει στις προσωπικές επιλογές.", axis: "social", reverse: true, weight: 1.1 },
  { id: "S18", text: "Η εθνική ταυτότητα πρέπει να προστατεύεται από εξωτερικές επιρροές.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S19", text: "Η διαφορετικότητα πρέπει να ενθαρρύνεται ενεργά.", axis: "social", reverse: true, weight: 1.0 },
  { id: "S20", text: "Η κοινωνική σταθερότητα είναι πιο σημαντική από την ατομική αυτονομία.", axis: "social", reverse: false, weight: 1.0 },
  { id: "S21", text: "Η κυβέρνηση πρέπει να περιορίζει την παραπληροφόρηση στο διαδίκτυο.", axis: "social", reverse: false, weight: 0.9 },
  { id: "S22", text: "Οι πολίτες πρέπει να έχουν πλήρη έλεγχο των προσωπικών τους δεδομένων.", axis: "social", reverse: true, weight: 1.2 },
  { id: "S23", text: "Η κοινωνία πρέπει να προσαρμόζεται στις νέες αξίες.", axis: "social", reverse: true, weight: 1.0 },
  { id: "S24", text: "Οι αρχές πρέπει να έχουν ευρύτερες εξουσίες σε περιόδους κρίσης.", axis: "social", reverse: false, weight: 1.0 },
];
