#!/usr/bin/env node
// EKA-48/49: public head-metadata inventory and deterministic sitemap generator.
// Dependency-free. The sitemap is rendered from scripts/sitemap.sources.json;
// each static entry pins the sha256 of its source file plus the git date of the
// last commit that changed it, so drift is detectable without git history.
//
//   node scripts/public-seo.mjs --check     verify docs/sitemap.xml + source hashes (CI, no git needed)
//   node scripts/public-seo.mjs --update    refresh changed entries from git, rewrite docs/sitemap.xml
//   node scripts/public-seo.mjs --rebuild   recompute every lastmod from git history
//   node scripts/public-seo.mjs --matrix    print the metadata matrix (markdown)
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SOURCES_FILE = 'scripts/sitemap.sources.json';
export const SITEMAP_FILE = 'docs/sitemap.xml';

const read = (rel) => readFileSync(join(ROOT, rel));

export const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

export function loadSources() {
  return JSON.parse(read(SOURCES_FILE).toString('utf8'));
}

const xmlEscape = (v) => String(v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function renderSitemap(sources) {
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Generated by scripts/public-seo.mjs from ${SOURCES_FILE}; do not edit by hand. -->`,
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ];
  for (const e of sources.entries) {
    lines.push('  <url>', `    <loc>${xmlEscape(sources.base + e.loc)}</loc>`);
    if (e.lastmod) lines.push(`    <lastmod>${e.lastmod}</lastmod>`);
    for (const [lang, href] of Object.entries(e.alternates || {})) {
      lines.push(`    <xhtml:link rel="alternate" hreflang="${lang}" href="${xmlEscape(sources.base + href)}"/>`);
    }
    lines.push(`    <changefreq>${e.changefreq}</changefreq>`, `    <priority>${e.priority}</priority>`, '  </url>');
  }
  lines.push('</urlset>', '');
  return lines.join('\n');
}

function git(args) {
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', env: { ...process.env, TZ: 'UTC' } }).trim();
}

// UTC committer date of the last commit that touched `rel`. Refuses shallow
// clones and uncommitted source changes so the value is reproducible.
export function gitLastmod(rel) {
  if (git(['rev-parse', '--is-shallow-repository']) === 'true') {
    throw new Error('shallow clone: lastmod needs full history (git fetch --unshallow)');
  }
  if (git(['status', '--porcelain', '--', rel]) !== '') {
    throw new Error(`${rel} has uncommitted changes; commit the page first, then regenerate the sitemap`);
  }
  const date = git(['log', '-1', '--format=%cd', '--date=format-local:%Y-%m-%d', '--', rel]);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error(`${rel}: no git history`);
  return date;
}

export function sourceDrift(sources) {
  const drift = [];
  for (const e of sources.entries) {
    if (!e.source) continue;
    const actual = sha256(read(e.source));
    if (actual !== e.sha256) drift.push(`${e.source}: content changed since lastmod ${e.lastmod}`);
  }
  return drift;
}

export function checkSitemap() {
  const sources = loadSources();
  const problems = sourceDrift(sources);
  if (read(SITEMAP_FILE).toString('utf8') !== renderSitemap(sources)) {
    problems.push(`${SITEMAP_FILE} differs from the rendering of ${SOURCES_FILE}`);
  }
  return problems;
}

function update({ all }) {
  const sources = loadSources();
  for (const e of sources.entries) {
    if (!e.source) continue;
    const actual = sha256(read(e.source));
    if (all || actual !== e.sha256) {
      e.lastmod = gitLastmod(e.source);
      e.sha256 = actual;
    }
  }
  writeFileSync(join(ROOT, SOURCES_FILE), `${JSON.stringify(sources, null, 2)}\n`);
  writeFileSync(join(ROOT, SITEMAP_FILE), renderSitemap(sources));
}

// --- head metadata inventory -------------------------------------------------

const attr = (tag, name) => {
  const m = tag.match(new RegExp(`\\s${name}\\s*=\\s*"([^"]*)"`, 'i'));
  return m ? m[1] : null;
};

export function inspectPage(rel) {
  const html = read(rel).toString('utf8');
  const head = html.split(/<\/head>/i)[0];
  const metas = [...head.matchAll(/<meta\b[^>]*>/gi)].map((m) => m[0]);
  const links = [...head.matchAll(/<link\b[^>]*>/gi)].map((m) => m[0]);
  const meta = (key, value) => metas.filter((t) => attr(t, key) === value).map((t) => attr(t, 'content'));
  const og = {};
  const twitter = {};
  for (const t of metas) {
    const p = attr(t, 'property');
    const n = attr(t, 'name');
    if (p && p.startsWith('og:')) og[p.slice(3)] = attr(t, 'content');
    if (n && n.startsWith('twitter:')) twitter[n.slice(8)] = attr(t, 'content');
  }
  const jsonLd = [...html.matchAll(/<script\b[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/gi)].map((m) => {
    try {
      JSON.parse(m[1]);
      return true;
    } catch {
      return false;
    }
  });
  return {
    path: rel,
    title: (head.match(/<title>([\s\S]*?)<\/title>/i) || [])[1] || null,
    description: meta('name', 'description'),
    robots: meta('name', 'robots'),
    canonical: links.filter((l) => attr(l, 'rel') === 'canonical').map((l) => attr(l, 'href')),
    hreflang: links.filter((l) => attr(l, 'hreflang')).map((l) => ({ lang: attr(l, 'hreflang'), href: attr(l, 'href') })),
    og,
    twitter,
    jsonLd,
  };
}

export const REQUIRED_OG = ['type', 'url', 'title', 'description', 'image', 'locale', 'site_name'];
export const REQUIRED_TWITTER = ['card', 'title', 'description', 'image'];

function matrix() {
  const sources = loadSources();
  const out = ['| Page | canonical = loc | og | twitter | hreflang | JSON-LD (ok/total) | lastmod |', '|---|---|---|---|---|---|---|'];
  for (const e of sources.entries.filter((x) => x.source)) {
    const p = inspectPage(e.source);
    const og = REQUIRED_OG.filter((k) => p.og[k]).length;
    const tw = REQUIRED_TWITTER.filter((k) => p.twitter[k]).length;
    const hl = p.hreflang.map((h) => h.lang).join('+') || '—';
    const canon = p.canonical.length === 1 && p.canonical[0] === sources.base + e.loc ? 'yes' : 'NO';
    out.push(`| ${e.source} | ${canon} | ${og}/${REQUIRED_OG.length} | ${tw}/${REQUIRED_TWITTER.length} | ${hl} | ${p.jsonLd.filter(Boolean).length}/${p.jsonLd.length} | ${e.lastmod} |`);
  }
  return out.join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const mode = process.argv[2] || '--check';
  if (mode === '--check') {
    const problems = checkSitemap();
    for (const p of problems) console.error(`sitemap drift: ${p}`);
    if (problems.length) {
      console.error('fix: commit the page change, then run `node scripts/public-seo.mjs --update` and commit the result');
      process.exit(1);
    }
    console.log('sitemap ok');
  } else if (mode === '--update' || mode === '--rebuild') {
    update({ all: mode === '--rebuild' });
    console.log(`wrote ${SOURCES_FILE} and ${SITEMAP_FILE}`);
  } else if (mode === '--matrix') {
    console.log(matrix());
  } else {
    console.error('usage: node scripts/public-seo.mjs [--check|--update|--rebuild|--matrix]');
    process.exit(2);
  }
}
